### ISSUE TITLE
v3 skips blank elements in a sequence whereas v2 does not

### ISSUE THREAD

**Issue by jotego** [go-yaml/yaml#1011]
The following YAML:

```
  - name: idle6 # waste 6 ucycles
    start: 0x42
    seq:
      - # 1
      - # 2
      - # 3
      - # 4
      - # 5
      - ret_jsr #6
```
Where seq is read into a `[]string` will produce 6 entries in go-yaml/v2 but only one in go-yaml/v3. I believe the correct behavior is that of v2. The empty elements should have been added as empty strings in the slice.
