### ISSUE TITLE
"On" and "Off" are interpreted as bool values

### ISSUE THREAD

**Issue by imax9000** [go-yaml/yaml#105]
https://github.com/go-yaml/yaml/blob/d466437aa4adc35830964cffc5b5f262c63ddcb4/resolve.go#L36

This makes it impossible to properly convert the next piece of YAML into JSON:

``` yaml
On:
  stuff: stuff
Off:
  stuff: stuff
```

Core schema in YAML 1.2 defines only a few variations of "true" and "false" as valid boolean values: http://www.yaml.org/spec/1.2/spec.html#id2805071
