### ISSUE TITLE
Empty array element is bypassed in v3

### ISSUE THREAD

**Issue by jotego** [go-yaml/yaml#1063]
This array gets parsed as two elements in v2:
``` YAML
banks:
  -
  - buses:
      - name: cart0
        addr_width: 21
```
So there is a banks[0] (empty) and a banks[1]. However, parsing the same with [v3](gopkg.in/yaml.v3) results in getting a sngle banks[0] element with the content of the second YAML entry.
I believe this behavior is wrong. It should return two elements.
