### ISSUE TITLE
Unmarshaling/Marshaling of map[string]Struct

### ISSUE THREAD

**Issue by alecbenson** [go-yaml/yaml#114]
Seems like I go-yaml will not marshal/unmarshal any string-struct maps. Here is an example I found online that exhibits the issue:

``` go
package main

import (
    "fmt"
    "gopkg.in/yaml.v2"
)

type T struct {
    cn     string
    street string
}

func main() {
    names := []string{"kasi", "remya", "nandan"}

    m := make(map[string]map[string]T, len(names))
    m["uid"] = make(map[string]T)
    for _, name := range names {
        m["uid"][name] = T{cn: "Chaithra", street: "fkmp"}
    }
    fmt.Println(m)

    y, _ := yaml.Marshal(&m)

    fmt.Println(string(y))
}
```

Output:

```
map[uid:map[kasi:{Chaithra fkmp} remya:{Chaithra fkmp} nandan:{Chaithra fkmp}]]
uid:
  kasi: {}
  nandan: {}
  remya: {}
```

This should marshal into the yaml version of the printed map, right?
