### ISSUE TITLE
Feature request: case-insensitive keys when Unmarshalling ?

### ISSUE THREAD

**Issue by moul** [go-yaml/yaml#123]
So we can load files like these:

``` yaml
hosts:
  toto:
    hostname: 1.2.3.4
    port: 42
```

As well as

``` yaml
Hosts:
  toto:
    HostName: 1.2.3.4
    Port: 42
```

Using

``` go
type File struct {
  Hosts: []Host `yaml:Hosts`,
}

type Host struct {
  HostName: string `yaml:HostName`
  Port: int `yaml:Port`
}
```
