### ISSUE TITLE
Is there a way to unmarshal a yaml value into one of two types?

### ISSUE THREAD

**Issue by eidge** [go-yaml/yaml#128]
My yams looks like this:

``` yaml
# ...
dir:
  - controllers
  - routes
  - models
  - specs:
    - models
    - controllers
# ...
```

I'm using the following struct to unmarshal the yaml:

``` go
type config struct {
  // ...
  Dir []BoilplateDir
  // ...
}

type BoilplateEmptyDir string
type BoilplateNestedDir map[string]interface{}

type BoilplateDir interface {
        HasNestedDirs() bool
}

func (*BoilplateEmptyDir) HasNestedDirs() bool  { return false }
func (*BoilplateNestedDir) HasNestedDirs() bool { return true }
```

The unmarshaling fails with: `panic: reflect.Set: value of type string is not assignable to type parser.BoilplateDir`.

Is there a way to do the unmarshaling this way? Or should I just use a `interface{}``and unbox the values manually?
