### ISSUE TITLE
Unmarshalling ignoring yaml instruction

### ISSUE THREAD

**Issue by tracyde** [go-yaml/yaml#141]
Given the following structs

``` go
type Metadata struct {
    StemcellCriteria         StemcellInfo `yaml: "stemcell_criteria"` // this does not work
    ProvidesProductVersions []ProductVersion `yaml: "provides_product_versions"` // this does not work
}

type StemcellInfo struct {
    OS          string `yaml: "os"`
    RequiresCPI bool   `yaml: "requires_cpi"`
    Version     string `yaml: "version"`
}

type ProductVersion struct {
    Name    string
    Version string
}
```

And the following yaml

``` yaml

---
stemcell_criteria:
  os: ubuntu-trusty
  requires_cpi: false
  version: '2989'

provides_product_versions:
  - name:    'p-concourse'
    version: '0.62.0'
```

Calling `yaml.Unmarshal` with the `Metadata` struct does not work. Neither StemcellCriteria or ProvidesProductVersions are populated.

If I rename `StemcellCriteria` and `ProvidesProductVersions` in the `Metadata` struct to `Stemcell_Criteria` and `Provides_Product_Versions` respectively, then `yaml.Unmarshal` works as expected populating each.
