### ISSUE TITLE
Access to metadata in tags?

### ISSUE THREAD

**Issue by lox** [go-yaml/yaml#150]
I'm trying to access the local tags used in some YAML I'm parsing:

``` yaml
  LaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      AssociatePublicIpAddress: true
      InstanceMonitoring: true
      SecurityGroups: [ $(InstanceSecurityGroup) ]
      ImageId: $(AWSRegionToAMI[$(AWS::Region)][AMIID])
      InstanceType: $(InstanceType)
      IamInstanceProfile: $(EC2InstanceProfile)
      KeyName: $(KeyName)
      UserData: !Base64 |
        #!/bin/bash -xve
        yum install -y aws-cfn-bootstrap
        /opt/aws/bin/cfn-init -v --stack $(AWS::StackName) --resource LaunchConfiguration --region $(AWS::Region)
        /opt/aws/bin/cfn-signal -e \$? --stack $(AWS::StackName) --resource ECSAutoScalingGroup --region $(AWS::Region)
```

I'm specifically interested in accessing the `!Base64` local tag, which seems to be dropped when parsing. Is there any way to get access to it?
