### ISSUE TITLE
YAML spec violation: Duplicate keys are silently ignored, and parser selects incorrect key

### ISSUE THREAD

**Issue by RichiH** [go-yaml/yaml#154]
As per https://github.com/prometheus/prometheus/issues/1275 :

If you run with a configuration like:

```
scrape_configs: <<<<<<<<<<<<<< this is discarded
  - job_name: 'prometheus_system'
    target_groups:
    - targets: ['localhost:9100']

scrape_configs:
  - job_name: 'foo_system'
    target_groups:
    - targets: ['foot:9100']
```

the former `scrape_configs` is silently discarded. While that's the obvious case, constructs like

```
scrape_configs: <<<<<<<<<<<<<< this is discarded
  - job_name: 'prometheus_system'
    target_groups:
    - targets: ['localhost:9100']

rule_files:
  - 'prometheus.rules'

scrape_configs:
  - job_name: 'foo_system'
    target_groups:
    - targets: ['foo:9100']
```

are silently discarded as well.

Raising an error would be appreciated, and suggested by the YAML specs, in this situation.

Also, as @fabxc notes, http://yaml.org/spec/1.1/#id932806 says that the first, not the last, occurence should be valid.
