### ISSUE TITLE
Default Value

### ISSUE THREAD

**Issue by johscheuer** [go-yaml/yaml#165]
Hello,

I wanted to ask if it's possible to redefine the zero values for `int`. For example I need something like this:

``` yaml
...
  # int32
  max: 2147483647
  min: -2147483648
```

If the value is set it should use the specified value and if there is no value specified it should use the defined zero/default value. Sadly I can't use the `0` as zero value because it is a valid value for min/max. 

My current solution is to use a `string` instead of `int`.
