### ISSUE TITLE
Accessing Map key in the node

### ISSUE THREAD

**Issue by khash** [go-yaml/yaml#177]
If I have a yaml like this:

```
super:
  node1:
    child: 1
  node2:
   child: 2
```

I can define it like this:

```
type Node struct {
  Child string `yaml:"child"`
}

type Super struct {
  Nodes map[string]Node
}
```

Is there a way to know the name of the node (string key in the map) from within the `Node` struct?
