### ISSUE TITLE
Rails like Config

### ISSUE THREAD

**Issue by degendra** [go-yaml/yaml#198]
Is it possible to parse rails like database config?

```
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: postgres
  password: 9841

development:
  <<: *default
  database: db_dev
  host: localhost
  username: postgres
  password: 1234  
```
