### ISSUE TITLE
Error reported on previous line number

### ISSUE THREAD

**Issue by deepakjois** [go-yaml/yaml#205]
Given the file:

``` yaml

---
GENERATOR:
  PackageName: cgogentest
  PackageDescription: "Package harfbuzz provides Go bindings for Harfbuzz"
  PackageLicense: "THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS."
  PkgConfigOpts: [harfbuzz]
  Includes: [hb.h]

PARSER:
  IncludePaths:
    - /usr/include
  SourcesPaths:
    - cgogentest/cgogentest.h

TRANSLATOR:
  ConstRules:
    defines: expand
  PtrTips:
    function:
      - {target: "_buffer_serialize_list_formats$", self: arr, tips: [ref]}
      - {target: ".", tips:[sref,sref,sref,sref,sref]}
```

and code

```
package main

import (
    "io/ioutil"
    "log"

    "gopkg.in/yaml.v2"
)

func main() {
    data, err := ioutil.ReadFile("lino.yaml")
    if err != nil {
        log.Fatal(err)
    }

    m := make(map[interface{}]interface{})
    err = yaml.Unmarshal([]byte(data), &m)
    if err != nil {
        log.Fatalf("error: %v", err)
    }
}
```

I get the error:

```
2016/09/25 19:57:55 error: yaml: line 20: found unexpected ':'
```

The line number is actually 21, but it is reported as 20. Why is this happening? Can this be fixed? It can be very confused when trying to nail down the issue. Especially when the difference is a missing whitespace character.
