### ISSUE TITLE
yaml.Marshal loses spaces when writing/printing

### ISSUE THREAD

**Issue by FilBot3** [go-yaml/yaml#207]
Using the following YAML file, and GO code, when I run the `yaml.Marshal` function it seems to lose the spaces that are desired. Is there a way to preserve those, or am I doing this wrong? It also seems to be stripping the `---` from the top of the file. What do I need to do to account for that? 

The YAML file

``` yaml

---
owner: "Phillip Dudley"
initialized: "2012-10-31T15:50:13.793654Z"
time_data:
  - action: "start"
    time: "2012-10-31T15:50:13.793654Z"
  - action: "stop"
    time: "2012-10-31T16:00:00.000000Z"
```

The GO code

``` go
package main

import (
    "fmt"
    "gopkg.in/yaml.v2"
    "io/ioutil"
    "log"
    "time"
)

// Top level YAML Structure
type Date_File struct {
    Owner    string      `yaml:"owner"`
    Init     time.Time   `yaml:"initialized"`
    TimeData []Time_Data `yaml:"time_data"` // slice, acting as map
}

// child to Date_File under TimeData
type Time_Data struct {
    //
    Action string    `yaml:"action"`
    Time   time.Time `yaml:"time"`
}

func checkerr(err error) {
    if err != nil {
        log.Fatal(err)
    }
}

// Read in a sample YAML file
func read() (td *Date_File) {
    //td := &Date_File{}
    gtt_config, err := ioutil.ReadFile("go_time_tracker.yml")
    checkerr(err)
    err = yaml.Unmarshal(gtt_config, &td)
    checkerr(err)
    return td
}

func main() {
    // Read in the YAML flle
    time_data := read()
    // Show the data in the reference
    fmt.Println(time_data)
    // Attempt to print the Array's first element
    fmt.Println(time_data.TimeData[0])
    // Display the key, Action's value
    fmt.Println(time_data.TimeData[0].Action)
    // Print the Owner.
    fmt.Println(time_data.Owner)

    // Marshal the YAML
    m_time_data, err := yaml.Marshal(&time_data)
    checkerr(err)

    fmt.Println(string(m_time_data))

    // Writing to a file.
    err = ioutil.WriteFile("new_go_time_tracker.yml", m_time_data, 0666)
    checkerr(err)
}
```

The resulting YAML

``` yaml
owner: Phillip Dudley
initialized: 2012-10-31T15:50:13.793654Z
time_data:
- action: start
  time: 2012-10-31T15:50:13.793654Z
- action: stop
  time: 2012-10-31T16:00:00Z
```
