### ISSUE TITLE
return ordered mappings?

### ISSUE THREAD

**Issue by termie** [go-yaml/yaml#22]
in applications the order of things in yaml and json tend to matter, but it appears we're using a map[interface{}]interface{} as the underlying datastructure for what are conceptually ordered maps.

Even after implementing an OrderedMap I can't populate its keys in the order specified in the yaml because it is returned with go's officially randomly sorted maps. Most other parsers in other languages i've tried return an ordered mapping for something like this:

```
- s3sync:
    key_id: $AWS_ACCESS_KEY_ID
    key_secret: $AWS_SECRET_ACCESS_KEY
    bucket_url: $AWS_BUCKET_URL
    source_dir: build/
```

becomes:

```
{"sync": {"key_id": ...., "key_secret": ...}}
```
