### ISSUE TITLE
Generate yaml with nested list of structs

### ISSUE THREAD

**Issue by Smana** [go-yaml/yaml#228]
Hi guys,

i'm trying to generate an Ansible playbook which is in yaml format. 
I want to create a file with the following content:

```
---
- hosts: "localhost"
  become: false
  gather_facts: false
  tasks:
    - name: "Provision GCE nodes instances"
      gce:
        image: debian-8
        instance_names: smanatest-0vkm7m,smanatest-xwvboo,smanatest-chl6tm'
        machine_type: n1-standard-1
        pem_file: REDACTED
        project_id: REDACTED
        service_account_email: REDACTED
        zone: us-central1-c
      register: gce_nodes
    - name: "Generate a file with nodes list"
      content: '{{gce_nodes.instance_data}}'
      dest: /home/smana/.kargo/nodes_instances.json
    - name: "Wait until SSH is available"
      local_action:
        host: '{{item.public}}'
        module: wait_for
        port: 22
        timeout: 600
        state: starded
        with_items: '{{gce_nodes.instance_data}}'
```

I tried that, but i didn't find a way to parse properly the list of tasks.
```
var data = `
hosts: "localhost"
become: false
gather_facts: false
tasks:
  name:
  gce:
    image: debian-8
    instance_names: smanatest-0vkm7m,smanatest-xwvboo,smanatest-chl6tm'
    machine_type: n1-standard-1
    pem_file: REDACTED
    project_id: REDACTED
    service_account_email: REDACTED
    zone: us-central1-c
    register: gce_nodes,
  name: "Generate a file with nodes list"
  content: '{{gce_nodes.instance_data}}'
  dest: /home/smana/.kargo/nodes_instances.json,
  name: "Wait until SSH is available"
  local_action:
    host: '{{item.public}}'
    module: wait_for
    port: 22
    timeout: 600
    state: starded
    with_items: '{{gce_nodes.instance_data}}'
`

type T struct {
	Host        string `yaml:"host"`
	Become      bool   `yaml:"become"`
	GatherFacts bool   `yaml:"gather_facts"`
	Tasks       []struct {
		NameGce string `yaml:"name"`
		Gce     struct {
			Image               string `yaml:"image"`
			InstanceNames       string `yaml:"instance_names"`
			MachineType         string `yaml:"machine_type"`
			PemFile             string `yaml:"pem_file"`
			ProjectID           string `yaml:"kargo-ci-1"`
			ServiceAccountEmail string `yaml:"service_account_email"`
			Zone                string `yaml:"zone"`
		}
		Register    string `yaml:"register"`
		NameCopy    string `yaml:"name"`
		Content     string `yaml:"content"`
		Dest        string `yaml:"dest"`
		NameWaitFor string `yaml:"name"`
		LocalAction struct {
			Host      string `yaml:"host"`
			Module    string `yaml:"module"`
			Port      int64  `yaml:"port"`
			Timeout   int64  `yaml:"timeout"`
			State     string `yaml:"state"`
			WithItems string `yaml:"with_items"`
		}
	} `yaml:",flow"`
}
```

Could you please give me a hand ?

Regards,
Smana
