### ISSUE TITLE
yaml.Unmarshal with multiple document structure

### ISSUE THREAD

**Issue by juev** [go-yaml/yaml#232]
yaml spec v1.2 contained information about files with multiple documents:
http://www.yaml.org/spec/1.2/spec.html

> YAML uses three dashes (“---”) to separate directives from document content. This also serves to signal the start of a document if no directives are present. Three dots ( “...”) indicate the end of a document without starting a new one, for use in communication channels.

Example:
```yaml
# Ranking of 1998 home runs
---
- Mark McGwire
- Sammy Sosa
- Ken Griffey

# Team ranking
---
- Chicago Cubs
- St Louis Cardinals
```

Example with `...`:
```yaml
---
time: 20:03:20
player: Sammy Sosa
action: strike (miss)
...
---
time: 20:03:47
player: Sammy Sosa
action: grand slam
...
```

How I can use goyaml with these files?? 

> Multi-document unmarshalling is not yet implemented, and base-60 floats from YAML 1.1 are purposefully not supported since they're a poor design and are gone in YAML 1.2.

This feature is planned for implementation in the future?
