### ISSUE TITLE
Marshal creates explicit subsections for items inherited from other structs

### ISSUE THREAD

**Issue by ghost** [go-yaml/yaml#236]
for example
```
type CompletePackageInfo struct {
	OveralPackageInfo
	TarballNameParsingPackageInfo
	TarballServerTraversePackageInfo
	BuildingPackageInfo
	CategorizationPackageInfo
}

type OveralPackageInfo struct {
	Description string `json:"description" yaml:"description"`
	HomePage    string `json:"home_page" yaml:"home_page"`

	Removable          bool `json:"removable" yaml:"removable"`
	Reducible          bool `json:"reducible" yaml:"reducible"`
	NonInstallable     bool `json:"non_installable" yaml:"non_installable"`
	Deprecated         bool `json:"deprecated" yaml:"deprecated"`
	PrimaryInstallOnly bool `json:"only_primary_install" yaml:"only_primary_install"`

	BuildDeps   []string `json:"build_deps" yaml:"build_deps"`
	SODeps      []string `json:"so_deps" yaml:"so_deps"`
	RunTimeDeps []string `json:"runtime_deps" yaml:"runtime_deps"`
}

type TarballNameParsingPackageInfo struct {
	BaseName    string `json:"basename" yaml:"basename"`
	VersionTool string `json:"version_tool" yaml:"version_tool"`
}

type TarballServerTraversePackageInfo struct {
	Filters            string   `json:"filters" yaml:"filters"`
	SourcePathPrefixes []string `json:"source_path_prefixes" yaml:"source_path_prefixes"`
}

type BuildingPackageInfo struct {
	BuilderName string `json:"buildscript" yaml:"buildscript"`
}

type CategorizationPackageInfo struct {
	Tags []string `json:"tags" yaml:"tags"`
}
```
marshals to
```
overalpackageinfo:
  description: write something here, please
  home_page: http://www.gnome.org
  removable: true
  reducible: true
  non_installable: false
  deprecated: false
  only_primary_install: false
  build_deps: []
  so_deps: []
  runtime_deps: []
tarballnameparsingpackageinfo:
  basename: gnome-terminal
  version_tool: ""
tarballservertraversepackageinfo:
  filters: ""
  source_path_prefixes: []
buildingpackageinfo:
  buildscript: gnome_terminal
categorizationpackageinfo:
  tags: []
```
while same struct marshaled with json
```
{"description":"write something here, please",
"home_page":"http://www.gnome.org",
"removable":true,
"reducible":true,
"non_installable":false,
"deprecated":false,
"only_primary_install":false,
"build_deps":[],
"so_deps":[],
"runtime_deps":[],
"basename":
"gnome-terminal",
"version_tool":"",
"filters":"",
"source_path_prefixes":[],
"buildscript":"gnome_terminal",
"tags":[]}
```
