### ISSUE TITLE
omitempty flag skipping valid time.Time 

### ISSUE THREAD

**Issue by bbengfort** [go-yaml/yaml#244]
I'm having a slight problem that I'd be happy to investigate and submit a PR for, but wanted to get your feedback first. It looks like time.Time values inside of a struct are not being serialized with the `omitempty` flag, even though they contain a valid time. My test case:

```go
type Record struct {
    Name string `yaml:"name,omitempty"` 
    Created time.Time `yaml:"created,omitempty"` 
}

func main() {
    records := []*Record{&Record{"foo", time.Now()}, &Record{"bar", time.Now()}}
    data, _ := yaml.Marshal(records)
    ioutil.WriteFile("records.yaml", data, 0644) 
}
```

The output for this is:

```yaml
- name: foo
- name: bar
```

Whereas the output for a `Record` struct defined without `omitempty` is:

```yaml
- name: foo
  created: 2017-03-02T07:58:08.116971948-05:00
- name: bar
  created: 2017-03-02T07:58:08.116972021-05:00
```

The desired behavior here is that if the `Created` field is the zero value for time, namely `time.Time{}`, then the created value isn't serialized, otherwise it is. In this case, time.Now() adds a valid time to the struct.
