### ISSUE TITLE
Does not support "inherited" structs

### ISSUE THREAD

**Issue by rnix** [go-yaml/yaml#37]
Given these stucts:

```
    type Path struct {
        Description string
        Paths       map[string]Path
    }

    type Top struct {
        Title       string
        Path
    }
```

I should be able to unmarshal a YAML like this:

```

---
  title: Recursive
  paths:
    a:
      paths:
        b:
          paths:
            c:
              description: Bottom
```

This works but should be the same thing as above:

```
    type Path struct {
        Description string
        Paths       map[string]Path
    }

    type Top struct {
        Title       string
        Paths    map[string]Path
    }
```
