### ISSUE TITLE
tags for nested struct parent field not parsed, but case insensitive is ok.

### ISSUE THREAD

**Issue by arcolife** [go-yaml/yaml#390]
[1] example.yaml:
```yaml
bot:
  some: 9 # random
  d: [3, 36]
# lskjfsd; random comments
a: Easy!
e: 10
```

struct in go:

```go
//snip 

type BottleNeck struct { 
     RenamedC int `yaml:"some"`
     D        []int
}

// Note: struct fields must be public in order for unmarshal to
// correctly populate the data.
type T struct {
        A string
	BottleNeck `yaml: "bot"`
	E int
}

main() {
        t := T{}
	datafile, err := ioutil.ReadFile("./example.yaml")
        err = yaml.Unmarshal(datafile, &t) // snip err checks
	fmt.Println(t.BottleNeck)
}
```
Output: 

```
{0 []}
```

expected:
```
{9 [3 36]}
```

this only works when yaml [2] is:

```yaml
bottleneck:
  some: 9 # random
  d: [3, 36]
# lskjfsd; random comments
a: Easy!
e: 10
```

note `bottleneck` [2] in parent field, as opposed to `bot` in [1] 

and that specifying ``` `yaml: "bot"` ``` doesn't have an effect. Am I using this wrong? or do we need a flag while unmarshalling too? 

I've read https://godoc.org/gopkg.in/yaml.v2#example-Unmarshal--Embedded but couldn't find a solution there.
