### ISSUE TITLE
Support retrieving list of anchors

### ISSUE THREAD

**Issue by eine** [go-yaml/yaml#394]
I'm trying to use a YAML file to define a list of groups and users:

``` yaml
- &g-admin
  scope: "/srv"
  allowCommands: true
  allowEdit: true
  allowNew: true
  commands:
    - git
    - svn
    - wget
- <<: *g-admin
  name: admin
- <<: *g-admin
  name: otheradmin
- &g-agroup
  allowCommands: false
  allowEdit: true
  allowNew: false
  commands: []
- <<: *g-agroup
  name: auser
  scope: "/srv/auser"
- <<: *g-agroup
  name: anotheruser
  scope: "/srv/anotheruser"
- name: otheruser
```

``` go
package main

import (
    "fmt"
    "gopkg.in/yaml.v2"
    "io/ioutil"
    "log"
)

type user struct {
	Name string
	Scope string
	AllowCommands bool `yaml:"allowCommands"`
	Commands []string
}

func main() {
    var c []user
    yamlFile, err := ioutil.ReadFile("conf.yml")
    if err != nil {
        log.Printf("yamlFile.Get err   #%v ", err)
    }
    err = yaml.Unmarshal(yamlFile, &c)
    if err != nil {
        log.Fatalf("Unmarshal: %v", err)
    }
    for _, v := range c {
      fmt.Println(v)
	}
}
```

``` bash
$ go run main.go 
{ /srv true [git svn wget]}
{admin /srv true [git svn wget]}
{otheradmin /srv true [git svn wget]}
{  true [ls]}
{auser /srv/auser true [ls]}
{anotheruser /srv/anotheruser true [ls]}
{otheruser  false []}
```

As shown, the five users are properly processed. However, I found no mechanism in this library to detect that the two additional entries with empty `Name` fields are YAML anchors (and to retrieve the anchor name).

There is no reference to either `alias` or `anchor` in the [doc](https://godoc.org/gopkg.in/yaml.v2) (see #391 and #374), so I think that this is not a supported feature yet.
