### ISSUE TITLE
Document selection of array element by value

### ISSUE THREAD

**Issue by rgm3** [go-yaml/yaml#398]
If there is a way to select an array element by value then please add it to the read examples.
Perhaps this ticket could be blocked by "add a way to select portions of the array by value."

For example, given:
```yaml
outputs:
  - foo:
    enabled: false
  - bar:
    enabled: true
  - baz:
    cat: pretty
```

I'm hoping to understand how to select the 'baz' array element at index 2 to examine its interesting properties.  I'm also hoping to understand how to select the "bar" element at index 1 by filtering for "enabled=true."
