### ISSUE TITLE
cannot unmarshal !!map into string (but it's a struct)

### ISSUE THREAD

**Issue by elegos** [go-yaml/yaml#406]
Hello!

Using `gopkg.in/yaml.v2@v2.2.1` here. I've got a simple configuration file written in yaml and I'm trying to parse it using this library.

The problem is that it returns me the following error:

```  line 3: cannot unmarshal !!map into string```

This is the sample code:
```go
package conf

import (
	"io/ioutil"

	yaml "gopkg.in/yaml.v2"
)

type Configuration struct {
	Listen struct {
		Unix struct {
			enabled bool   `yaml:"enabled"`
			socket  string `yaml:"socket"`
		} `yaml:"unix"`
		Tcp struct {
			enabled bool   `yaml:"enabled"`
			port    uint16 `yaml:"port"`
		} `yaml:"tcp"`
	} `yaml:"listen"`
}

type rawConfiguration struct {
	Authentication Configuration `yaml:"authentication"`
}

func ReadConfiguration(path string) (configuration Configuration, err error) {
	yamlFile, err := ioutil.ReadFile(path)

	if err != nil {
		return configuration, err
	}

	rawConf := rawConfiguration{}
	err = yaml.Unmarshal(yamlFile, &rawConf)

	if err != nil {
		return configuration, err
	}

	configuration = rawConf.Authentication

	return configuration, err
}
```

Sample yml file:
```yaml
authentication:
  listen:
    unix:
      enabled: true
      socket: "/tmp/authentication.sock"
    tcp:
      enabled: true
      port: 13213
```

May you please tell me what I am doing wrong?

Thanks :)
