### ISSUE TITLE
Merge with overrides doesn't work in strict mode

### ISSUE THREAD

**Issue by juzna** [go-yaml/yaml#410]
When you merge dicts, it's allowed to override keys (http://yaml.org/type/merge.html).

Example 1:
```yaml
foo: &foo
  some: foo

bar:
  <<: *foo
  some: bar # override for `some`, should be allowed
```

Example 2:
```yaml
foo: &foo
  some: foo

bar: &bar
  some: bar

foobar:
  <<: [*foo, *bar]  # override for `some`, should be allowed
```

However, when using the strict mode (`unmarshalStrict`), you get the following error:
`key "some" already set in map`
