### ISSUE TITLE
Unpredictable order for marshalled maps

### ISSUE THREAD

**Issue by gustafj** [go-yaml/yaml#444]
The problem stated in #194 is not yet solved (as mentioned by @HeavyWombat in his comment https://github.com/go-yaml/yaml/issues/194#issuecomment-440818819).

Running his test on the current version creates unpredictable output, e.g.:
```
properties:
  cc:
    quota_definitions:
      q256MB:
        non_basic_services_allowed: true
      q2GB:
        non_basic_services_allowed: true
      q4GB:
        non_basic_services_allowed: true
```
vs
```
properties:
  cc:
    quota_definitions:
      q4GB:
        non_basic_services_allowed: true
      q256MB:
        non_basic_services_allowed: true
      q2GB:
        non_basic_services_allowed: true
```

What is the reason for using a custom (and error prone) implementation of string comparison in: https://github.com/go-yaml/yaml/blob/7b8349ac747c6a24702b762d2c4fd9266cf4f1d6/sorter.go#L39-L40 ?

Any particular reason why lexicographical ordering is unwanted / not sufficient as is the result of a simple `return a.String() < b.String()`?

_I opened a new issue as there seems to be no action in the closed one and to highlight the issue, hope that is ok_
