### ISSUE TITLE
Support CRLF endings

### ISSUE THREAD

**Issue by owlscode** [go-yaml/yaml#450]
## Witnessed behavior
`go-yaml` does not support CRLF line endings when reading a file directly (which would be the main use case). For instance, the following code won't work if the loaded file is written on Windows:
```go
type Auth struct {
	Customer struct {
		Key    string
		Secret string
	}
	App struct {
		Key    string
		Secret string
	}
}

func main() {
	data, err := ioutil.ReadFile("./secret.yml")
	if err != nil {
		fmt.Println(err.Error())
		os.Exit(1)
	}

	a := Auth{}
	err = yaml.Unmarshal(data, &a)
	if err != nil {
		fmt.Println(err.Error())
		os.Exit(1)
	}
	fmt.Println(a)
}
```
With the following file content:
```yaml
--- 
app:
  key: 10475405799b09120-vSkxPPI9HsWN61vO4DroQUGFpgNCs2
  secret: Z6nG4UInQVWx7Sagpmu6GsUYWZsvd5E6uIbPdlW8csfemaxm
customer:
  key: JA2PXLd8qeXTDpx7UccWsvp60V6
  secret: qOsUM6996LQSkRw9HsnxyU3EVJzACIOEUxCBTiOcTELTF800VVQ
```
Here's the error: `yaml: line 3: mapping values are not allowed in this context`

## Expected behavior
Just work as usual.
