### ISSUE TITLE
Add new node to yaml file

### ISSUE THREAD

**Issue by RaynDol** [go-yaml/yaml#452]
HI,

I've the following yaml file and I need to insert to it a new object (json) and to keep the structure the same

For example

lets say I’ve this yml file
```
version: 1
type: verbose
kind : bfr

# my list of applications
applications:
  - name: app1
    kind: nodejs
    path: app1
    exec:
      platforms: k8s
      builder: test

```
This is the json object which I need to insert
```
[

    {
        "comment: "Second app",
        "name": "app2",
        "kind": "golang",
        "path": "app2",
        "exec": {
            "platforms": "dockerh",
            "builder": "test"
        }
    }
]

```
 I need to add it to the yml file after the first application, (applications is array of application)
```
version: 1
type: verbose
kind : bfr

# my list of applications
applications:

#  First app
  - name: app1
    kind: nodejs
    path: app1
    exec:
      platforms: k8s
      builder: test

# Second app
  - name: app2
    kind: golang
    path: app2
    exec:
      platforms: dockerh
      builder: test

```
is it possible to add to the yaml file the new json object with the node capability  ? is there some example which I can use as reference?
