### ISSUE TITLE
panic on decoding malformed pointer usage in multi-document file

### ISSUE THREAD

**Issue by triodan** [go-yaml/yaml#468]
**Output**
Expected error, but got panic instead:
```
panic: attempted to parse unknown event: none [recovered]
	panic: attempted to parse unknown event: none

goroutine 1 [running]:
gopkg.in/yaml%2ev2.handleErr(0xc000059f38)
	/home/daniel/go/pkg/mod/gopkg.in/yaml.v2@v2.2.2/yaml.go:249 +0x9a
panic(0x4fb620, 0xc000010330)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
gopkg.in/yaml%2ev2.(*parser).parse(0xc0000b4000, 0x52d678)
	/home/daniel/go/pkg/mod/gopkg.in/yaml.v2@v2.2.2/decode.go:158 +0x256
gopkg.in/yaml%2ev2.(*Decoder).Decode(0xc000059f78, 0x4f5400, 0xc00000c240, 0x0, 0x0)
	/home/daniel/go/pkg/mod/gopkg.in/yaml.v2@v2.2.2/yaml.go:122 +0xdc
main.main()
	/home/daniel/gov/poc/main.go:24 +0x1d3
exit status 2

```
Reproducible when running the below code (Go 1.12.5) :
```go
package main

import (
        "io"
        "os"

        "gopkg.in/yaml.v2"
)

func main() {
        file, err := os.Open("test.yaml")
        if err != nil {
                panic(err)
        }

        d := yaml.NewDecoder(file)
        for {
                var k interface{}
                if err = d.Decode(&k); err == io.EOF {
                        break
                }
        }

}
```
With `test.yaml` contents being:
```yaml
---
metadata:
  labels: &labels
    project: test
    service: test
    env: staging
  name: test-staging
  namespace: test
spec:
  selector:
    &lt;&lt;: *labels
    service: test
---
kind: Deployment
metadata:
  name: test-staging
```
