### ISSUE TITLE
Is it possible to add tag to force yaml string field to use | notion

### ISSUE THREAD

**Issue by amurchick** [go-yaml/yaml#471]
Some times peoples needs editing saved multiline string in yaml-file.
But if decode and then encode this file
```yaml
string: |
  func (app *App) NewHttp() {
    app.startWs()
    router := mux.NewRouter()
    router.Use(app.commonHandler)
    // router.NotFoundHandler = handlers.CompressHandlerLevel(utils.MakeHttpCustomFileServer(cfg.FrontEndPath, "index.html"), gzip.BestCompression)
    router.HandleFunc("/ws", app.serveWs)
    // a.router.PathPrefix("/api/{method}").HandlerFunc(func(resp http.ResponseWriter, req *http.Request) {
    // 	vars := mux.Vars()
    // 	resp.Write([]byte("hello"))
    // })
    // a.router.Headers
    apiRouter := router.PathPrefix("/api").Subrouter()
    apiRouter.Handle("/auth", handlers.CompressHandlerLevel(http.HandlerFunc(app.apiAuthPost), 5)).Methods("POST")

    headersOk := handlers.AllowedHeaders([]string{"X-Requested-With", "Content-Type"})
    originsOk := handlers.AllowedOrigins([]string{"*"})
    methodsOk := handlers.AllowedMethods([]string{"GET", "HEAD", "POST", "PUT", "OPTIONS"})

    go func() {
      log.Info("Start linten on %#v", app.cfg.Listen)
      if err := http.ListenAndServe(app.cfg.Listen, handlers.LoggingHandler(os.Stdout, utils.LogHttpRequest(handlers.CORS(originsOk, headersOk, methodsOk)(router)))); err != nil {
        log.Fatal(err)
      }
    }()
  }
```

I am get not easy editable yaml-file:
```yaml
string: "func (app *App) NewHttp() {\n\t\t\tapp.startWs()\n\t\t\trouter :=                                                                            
    mux.NewRouter()\n\t\t\trouter.Use(app.commonHandler)\n\t\t\t// router.NotFoundHandler                                                                 
    = handlers.CompressHandlerLevel(utils.MakeHttpCustomFileServer(cfg.FrontEndPath,                                              
    \"index.html\"), gzip.BestCompression)\n\t\t\trouter.HandleFunc(\"/ws\", app.serveWs)\n\t\t\t//                                                       
    a.router.PathPrefix(\"/api/{method}\").HandlerFunc(func(resp http.ResponseWriter,                                         
    req *http.Request) {\n\t\t\t// \tvars := mux.Vars()\n\t\t\t// \tresp.Write([]byte(\"hello\"))\n\t\t\t//                                               
    })\n\t\t\t// a.router.Headers\n\t\t\tapiRouter := router.PathPrefix(\"/api\").Subrouter()\n\t\t\tapiRouter.Handle(\"/auth\",            
    handlers.CompressHandlerLevel(http.HandlerFunc(app.apiAuthPost), 5)).Methods(\"POST\")\n\n\t\t\theadersOk                                             
    := handlers.AllowedHeaders([]string{\"X-Requested-With\", \"Content-Type\"})\n\t\t\toriginsOk                                                         
    := handlers.AllowedOrigins([]string{\"*\"})\n\t\t\tmethodsOk := handlers.AllowedMethods([]string{\"GET\",                                             
    \"HEAD\", \"POST\", \"PUT\", \"OPTIONS\"})\n\n\t\t\tgo func() {\n\t\t\t\tlog.Info(\"Start                                              
    linten on %#v\", app.cfg.Listen)\n\t\t\t\tif err := http.ListenAndServe(app.cfg.Listen,                                                               
    handlers.LoggingHandler(os.Stdout, utils.LogHttpRequest(handlers.CORS(originsOk,                                                       
    headersOk, methodsOk)(router)))); err != nil {\n\t\t\t\t\tlog.Fatal(err)\n\t\t\t\t}\n\t\t\t}()\n\t\t}"                                                
```

Please add field tag for save string field in | notion.
Thank you!

**Comment by niemeyer** [comment]
There's something awkward going on there. You can use a yaml.Node in v3 to force the syntax, but the default behavior is to automatically encode as "|" any multi-line string precisely because that's much more pleasant to read in such cases. It looks like for some reason that logic is failing for you.

Let me have a look at this.

**Comment by niemeyer** [comment]
Somewhat curiously, the original libyaml code forbids literals in presence of tabs, which that string contains. From the spec I can't see why that'd be the case though. Even the example itself for literal formatting includes tabs, so I'm considering this as undesired behavior and fixed it in v3 with a56cad2.

**Comment by jsteenb2** [comment]
@niemeyer I believe I am seeing something similar with the gopkg.in/v3 branch `https://github.com/go-yaml/yaml/commit/fc94e3f7165204dd261b8d39d39a1e1773b931c9`. 

I'm getting the following, and this doesn't happen all the time just occasionally. The query below gets escaped:

```yaml
apiVersion: influxdata.com/v2alpha1
kind: Dashboard
metadata:
    name: System
spec:
    charts:
      - colors:
          - hex: '#00C9FF'
            name: laser
            type: text
        decimalPlaces: 2
        height: 1
        kind: Single_Stat
        name: Total Memory
        queries:
          - query: "from(bucket: v.bucket)\n  |> range(start: v.timeRangeStart)\n
                \ |> filter(fn: (r) => r._measurement == \"mem\")\n  |> filter(fn:
                (r) => r._field == \"total\")\n  |> last()\n  |> map(fn: (r) => ({r
                with _value: float(v: r._value) / 1024.0 / 1024.0 / 1024.0}))\n  |>
                yield(name: \"last\")\n  "
        suffix: ' GB'
        width: 2
    description: A collection of useful visualizations for monitoring your system
        stats
```

It would be preferable to have them be like the following for better readability:

```yaml
apiVersion: influxdata.com/v2alpha1
kind: Dashboard
metadata:
    name: System
spec:
    charts:
      - colors:
          - hex: '#00C9FF'
            name: laser
            type: text
        decimalPlaces: 2
        height: 1
        kind: Single_Stat
        name: Total Memory
        queries:
          - query: |-
                    from(bucket: v.bucket)
                      |> range(start: v.timeRangeStart)
                      |> filter(fn: (r) => r._measurement == "mem")
                      |> filter(fn: (r) => r._field == "total")
                      |> last()
                      |> map(fn: (r) => ({r with _value: float(v: r._value) / 1024.0 / 1024.0 / 1024.0}))
                      |> yield(name: "last")
        suffix: ' GB'
        width: 2
    description: A collection of useful visualizations for monitoring your system
        stats
```

references: https://github.com/influxdata/influxdb/issues/16632
