### ISSUE TITLE
"Safe" parsing options

### ISSUE THREAD

**Issue by Goodwine** [go-yaml/yaml#479]
Can go-yaml have options that do "safe" unmarshalling?
By "safe", I mean either failing with pointers/references, or parsing them as strings.

### Example input (from wiki):
```yaml
a: &a ["lol","lol","lol","lol","lol","lol","lol","lol","lol"]
b: &b [*a,*a,*a,*a,*a,*a,*a,*a,*a]
c: &c [*b,*b,*b,*b,*b,*b,*b,*b,*b]
d: &d [*c,*c,*c,*c,*c,*c,*c,*c,*c]
e: &e [*d,*d,*d,*d,*d,*d,*d,*d,*d]
f: &f [*e,*e,*e,*e,*e,*e,*e,*e,*e]
g: &g [*f,*f,*f,*f,*f,*f,*f,*f,*f]
h: &h [*g,*g,*g,*g,*g,*g,*g,*g,*g]
i: &i [*h,*h,*h,*h,*h,*h,*h,*h,*h]
```

### Example use:
```go
v := interface{}{}
err := yaml.UnmarshalSafe([]byte(data, &v))
if (err != nil) { panic(err) } 
fmt.Print(err)
```

### Example behavior 1:
Fail on any reference declaration
`panic: could not parse yaml line 1: references are not allowed on safe mode`

### Example behavior 2:
Allow reference declarations but don't allow using them
`panic: could not parse yaml line 2: pointers are not allowed on safe mode`

This allows defining `type V struct { A interface{} }` which can parse the property `a` since it doesn't use an "unsafe" feature

### Example behavior 3:
Fallback to strings, e.g. this is the result:
```
a: ["lol", ...]
b: ["*a", ...]
...
```

### Proposal
I think Behavior 2 is the best option out of the 3 I proposed here.
Also, I'm not aware of more "unsafe" YAML features and I'm just pointing out the only one I know, but would also throw an error with this proposed new function.
