### ISSUE TITLE
yaml.v3 interesting comment behavior

### ISSUE THREAD

**Issue by klautcomputing** [go-yaml/yaml#497]
Hey @niemeyer 

Given that we at Shopify are interested in making go-yaml work with comments and my colleagues previous PR https://github.com/go-yaml/yaml/pull/419 we two set out and wanted to see whether we can start using v3 in the same way as we use #419 so that we don't need to maintain our own fork anymore.

Our test cases are just a roundtrip through go-yaml.v3, unmarshal into nodes, and then marshal back into yaml. No manipulation on our end.

We are going to post a couple of test cases with comments, they are structured in the following way:
first we have an input block, which is just the file that we are handing to go-yaml.v3, e.g.
```
# comment 1
a: b
```
it will be followed by the node representation:
```
&{Kind:1 Style:0 Tag: Value: Anchor: Alias:<nil> Content:[0xc0003701e0] HeadComment: LineComment: FootComment: Line:2 Column:1}
    &{Kind:4 Style:0 Tag:!!map Value: Anchor: Alias:<nil> Content:[0xc000370280 0xc000370320] HeadComment: LineComment: FootComment: Line:2 Column:1}
        &{Kind:8 Style:0 Tag:!!str Value:a Anchor: Alias:<nil> Content:[] HeadComment:# comment 1 LineComment: FootComment: Line:2 Column:1}
        &{Kind:8 Style:0 Tag:!!str Value:b Anchor: Alias:<nil> Content:[] HeadComment: LineComment: FootComment: Line:2 Column:4}
```
last and most important the result from go-yaml
```
# comment 1
a: b
```
From now on they will just be in one code block to make our lives easier.

Case 1: The document foot comment moves up into a foot comment of the child "b"
```
# I should be a head comment
a:
  b: c

# I should be a document foot comment

&{Kind:1 Style:0 Tag: Value: Anchor: Alias:<nil> Content:[0xc0003500a0] HeadComment: LineComment: FootComment: Line:2 Column:1}
    &{Kind:4 Style:0 Tag:!!map Value: Anchor: Alias:<nil> Content:[0xc000350140 0xc0003501e0] HeadComment: LineComment: FootComment: Line:2 Column:1}
        &{Kind:8 Style:0 Tag:!!str Value:a Anchor: Alias:<nil> Content:[] HeadComment:# I should be a head comment LineComment: FootComment: Line:2 Column:1}
        &{Kind:4 Style:0 Tag:!!map Value: Anchor: Alias:<nil> Content:[0xc000350280 0xc000350320] HeadComment: LineComment: FootComment: Line:3 Column:3}
            &{Kind:8 Style:0 Tag:!!str Value:b Anchor: Alias:<nil> Content:[] HeadComment: LineComment: FootComment:# I should be a document foot comment Line:3 Column:3}
            &{Kind:8 Style:0 Tag:!!str Value:c Anchor: Alias:<nil> Content:[] HeadComment: LineComment: FootComment: Line:3 Column:6}
# I should be head comment
a:
    b: c
    # I should be a document foot comment
```

Case 2: Trying to figure out which node will own a comment we tested the following and were quite surprised by the extra newlines:
```
# comment 1
a: b
# comment 2
c: d
# comment 3

&{Kind:1 Style:0 Tag: Value: Anchor: Alias:<nil> Content:[0xc00036c140] HeadComment: LineComment: FootComment: Line:2 Column:1}
    &{Kind:4 Style:0 Tag:!!map Value: Anchor: Alias:<nil> Content:[0xc00036c1e0 0xc00036c280 0xc00036c320 0xc00036c3c0] HeadComment: LineComment: FootComment: Line:2 Column:1}
        &{Kind:8 Style:0 Tag:!!str Value:a Anchor: Alias:<nil> Content:[] HeadComment:# comment 1 LineComment: FootComment: Line:2 Column:1}
        &{Kind:8 Style:0 Tag:!!str Value:b Anchor: Alias:<nil> Content:[] HeadComment: LineComment: FootComment: Line:2 Column:4}
        &{Kind:8 Style:0 Tag:!!str Value:c Anchor: Alias:<nil> Content:[] HeadComment:# comment 2 LineComment: FootComment:# comment 3 Line:4 Column:1}
        &{Kind:8 Style:0 Tag:!!str Value:d Anchor: Alias:<nil> Content:[] HeadComment: LineComment: FootComment: Line:4 Column:4}
# comment 1
a: b


# comment 2
c: d
# comment 3
```

Case 3: I don't know what's going on at this point... The foot comment from Case 1 is now working correctly, but a lot of other things are weird and most importantly it swallows a line comment on "a":

```
# I should be a document head comment

# I am a head comment for "a"
a: # I should be a line comment for "a"
# I am a foot comment for "a"
  # I am a head comment for "b"
  b: c # I should be a line comment for "b/c"
  # I am a foot comment for "b"

# I should be a document foot comment

&{Kind:1 Style:0 Tag: Value: Anchor: Alias:<nil> Content:[0xc00033c140] HeadComment:# I should be a document head comment LineComment: FootComment:# I should be a document foot comment Line:4 Column:1}
    &{Kind:4 Style:0 Tag:!!map Value: Anchor: Alias:<nil> Content:[0xc00033c1e0 0xc00033c280] HeadComment: LineComment: FootComment: Line:4 Column:1}
        &{Kind:8 Style:0 Tag:!!str Value:a Anchor: Alias:<nil> Content:[] HeadComment:# I am a head comment for "a" LineComment: FootComment: Line:4 Column:1}
        &{Kind:4 Style:0 Tag:!!map Value: Anchor: Alias:<nil> Content:[0xc00033c320 0xc00033c3c0] HeadComment: LineComment: FootComment: Line:7 Column:3}
            &{Kind:8 Style:0 Tag:!!str Value:b Anchor: Alias:<nil> Content:[] HeadComment:# I am a foot comment for "a"
# I am a head comment for "b" LineComment:# I should be a line comment for "a" FootComment:# I am a foot comment for "b" Line:7 Column:3}
            &{Kind:8 Style:0 Tag:!!str Value:c Anchor: Alias:<nil> Content:[] HeadComment: LineComment:# I should be a line comment for "b/c" FootComment: Line:7 Column:6}
# I should be a document head comment

# I am a head comment for "a"
a:
    # I am a foot comment for "a"
    # I am a head comment for "b"
    b: c # I should be a line comment for "b/c"
    # I am a foot comment for "b"

# I should be a document foot comment
```

Are you interested in us trying to port our test cases from #419 to v3 to a) add some test coverage b) to find and potentially resolve these unexpected behaviors c) document comment behavior a bit more?

cheers @genevieveluyt + @klautcomputing
