### ISSUE TITLE
did not find expected key

### ISSUE THREAD

**Issue by tpdenk** [go-yaml/yaml#498]
I am given the following yaml:
```yaml
  description: >
      `yield` is a reserved identifier in strict mode code and may not be used
      as a label.
  es6id: 12.1.1
  negative:
    phase: parse
    type: SyntaxError
  flags: [onlyStrict]
```
(notice there are extra spaces at the beginning of each line)

I think the spaces are the problems, but:
* I have no influence over the YAML that I am given
* every YAML linter on the internet says it's valid yaml

Any workaround, or maybe this even is unwanted behaviour?
