### ISSUE TITLE
Unmarshaling complex type in yaml 

### ISSUE THREAD

**Issue by imjuni** [go-yaml/yaml#528]
Hi, 

I develop application using avro protocol. And I want manage avro schema using by go-yaml

But I don't find solution that support avro type

```
fields: 
  - type: string
    default: greeting
  - type:
    - string
    - null
```

`type` field can have two type, string and []string

How can I deal with go-yaml? 

Thank!
