### ISSUE TITLE
Serialization of `yaml.Node`

### ISSUE THREAD

**Issue by pstibrany** [go-yaml/yaml#575]
Hi,

we have a problem with serializing structs like this:

```
package main

import (
	"fmt"
	"time"

	"gopkg.in/yaml.v3"
)

type RuleNode struct {
	Record      yaml.Node         `yaml:"record,omitempty"`
	Alert       yaml.Node         `yaml:"alert,omitempty"`
	Expr        yaml.Node         `yaml:"expr"`
	For         time.Duration     `yaml:"for,omitempty"`
	Labels      map[string]string `yaml:"labels,omitempty"`
	Annotations map[string]string `yaml:"annotations,omitempty"`
}

func main() {
	rn := RuleNode{}
	rn.Expr.SetString("hello")
	rn.Alert.SetString("world")
	rn.For = time.Minute

	out, err := yaml.Marshal(rn)
	if err != nil {
		fmt.Println(err)
	} else {
		fmt.Println(string(out))
	}
}
```

Problem is of course that Record, Alert or Expr are defined as `yaml.Node` and not as a pointer to the node.

I was wondering if there is a reason why serialization of `yaml.Node` isn't currently supported by Yaml package directly, and if it would be possible to add such support (or if patch to add it is welcome).

Our problem is that the struct we want to serialize is [vendored](https://github.com/prometheus/prometheus/blob/84e6459c4d4196ff429af603fe97b2b40e168c15/pkg/rulefmt/rulefmt.go#L121) and it might be difficult to change (although I will probably try that path as well).

Thank you,
-Peter

**Comment by pstibrany** [comment]
Here is one more example, showing that Unmarshalling into yaml.Node works:

```
package main

import (
	"fmt"
	"time"

	"gopkg.in/yaml.v3"
)

type RuleNode struct {
	Record      yaml.Node         `yaml:"record,omitempty"`
	Alert       yaml.Node         `yaml:"alert,omitempty"`
	Expr        yaml.Node         `yaml:"expr"`
	For         time.Duration     `yaml:"for,omitempty"`
	Labels      map[string]string `yaml:"labels,omitempty"`
	Annotations map[string]string `yaml:"annotations,omitempty"`
}

const inp = `
alert: up_alert
expr: count(up) == 0
for: 5m
`

func main() {
	rn := RuleNode{}

	err := yaml.Unmarshal([]byte(inp), &rn)
	if err != nil {
		fmt.Println(nil)
	}

	fmt.Println("Parsed:", rn.Alert.Value, rn.Expr.Value, rn.For)

	out, err := yaml.Marshal(rn)
	if err != nil {
		fmt.Println(err)
	} else {
		fmt.Println(string(out))
	}
}
```

This prints 

```
Parsed: up_alert count(up) == 0 5m0s
alert:
    kind: 8
    style: 0
    tag: '!!str'
    value: up_alert
    anchor: ""
    alias: null
    content: []
    headcomment: ""
    linecomment: ""
    footcomment: ""
    line: 2
    column: 8
expr:
    kind: 8
    style: 0
    tag: '!!str'
    value: count(up) == 0
    anchor: ""
    alias: null
    content: []
    headcomment: ""
    linecomment: ""
    footcomment: ""
    line: 3
    column: 7
for: 5m0s
```
