### ISSUE TITLE
Option to accept int/floats as time.Duration/time.Time

### ISSUE THREAD

**Issue by XANi** [go-yaml/yaml#592]
Many applications serialize durations as int/float and timestamps as raw unix time, like (from Puppet):

```yaml
time:
  anchor: 0.001626505
  apt_key: 2.374957695
  catalog_application: 95.77198921469972
  concat_file: 0.000944676
  concat_fragment: 0.00161693
  ...
  last_run: 1585892661
```

would be useful to have a flag (like say `numeric`) that would allow ingesting/producing raw ints/floats instead of go-formatted time.Duration/time.Time for cooperation with apps that do that
