### ISSUE TITLE
v3: Consider providing pointer to parent yaml.Node

### ISSUE THREAD

**Issue by ahmetb** [go-yaml/yaml#598]
I'm happily using go-yaml.v3. However while using it I've noticed lack of links to parent `Node`s in each child node (i.e. `Node.Content`).

If this link was there, one could, for example, easily figure out path of certain Nodes in the doc tree easily by traversing the Nodes up recursively.

**Comment by niemeyer** [comment]
This would make the structure fully circular, and could also make aliases confusing since they are referenced out of place. Not sure the benefit is worth it. Closing this for now.

**Comment by iggy** [comment]
Did you ever find a workaround for this? I'm in a situation where this would definitely come in handy.

Something similar to the following:
```yaml
users:
  add:
    - name: iggy
      desc: the one the only
    - name: rocky
      desc: moose?
  del:
    - name: steve
      desc: annoying
    - name: molly
      desc: wog
```
```go
type User struct {
    Name string
    Desc string
    addOrDel string
}
func (u *User) UnmarshalYAML(node *value.Node) error {
    for i, n := range node.Content {
        switch n.Value {
        case "name":
            u.Name = node.Content[i+1].Value
        case "desc":
            u.Desc = node.Content[i+1].Value
        }
    }
    // something like this to access the parent's name
    // or would it be node.Parent.Parent.Value? ... I'm getting ahead of myself
    u.addOrDel = node.Parent.Value
}
```
being able to use a single struct to identify these with a field that was for add/del would be useful
