### ISSUE TITLE
Support for user defined schemas and types mapping

### ISSUE THREAD

**Issue by pawel-kedzior-sw** [go-yaml/yaml#605]
One of the coolest feature of yaml which I found when programming in other languages (C#/Java) was the ability to prepare a map of custom tags to concrete types and pass it to unmarshaler.
Example:

```
shapes:
   - !circle
      radius: 5
   - !square
      size: 2
```

By preparing a map of tags: '!circle' to a Circle type and '!square' to Square type, the 'shapes' field could be a list of AbstractShape (in Java/C#) or could be a slice of interface{} in Go.

The feature is equally applicable to single values, but the example with a collection is depicting it very well.

The feature is super useful because it makes the programming model very neat when you interpret the data.

As I tried to use the current yaml.v3, the best I could get is a map of properties. I couldn't also find out the details what was the original tag but I might have missed something.

I am requesting is to provide an API for unmarshaler to configure mapping in between the custom tags and concrete types and use it during unmarshaling to instantiate appropriate ones.

**Comment by pawel-kedzior-sw** [comment]
I am working on the proposal of the pull-request here:

https://github.com/go-yaml/yaml/compare/v3...pawel-kedzior-sw:feature/custom-user-tags?expand=1

**Comment by pawel-kedzior-sw** [comment]
Pull request: https://github.com/go-yaml/yaml/pull/636

**Comment by NightTsarina** [comment]
This would be a very useful addition. In particular, I would like to support including files by using a custom schema (like https://github.com/tanbro/pyyaml-include does), and this seems to be the only missing piece.

Example:

```yaml
--- # main.yaml
myconfig: !include [conf.d/*.yaml]

<<: !include localoptions.yaml

--- # conf.d/foo.yaml
name: foo
option: bar

--- # conf.d/foo2.yaml
name: foo2
option: baz

--- # localoptions.yaml
extra: false
```

Which would unmarshal exactly as if the input was:

```yaml
myconfig:
- name: foo
  option: bar
- name: foo2
  option: baz
extra: false
```
