### ISSUE TITLE
nested conf Unmarshalling

### ISSUE THREAD

**Issue by BigBoulard** [go-yaml/yaml#606]
Hi guys,

I'm struggling with the `gopkg.in/yaml.v3` package to parse my conf file. The variable supposed to contain the configuration vars remains empty, so I probably have missed something...

YAML file
```yaml
---
DBs:
  Src:
    protocol: xxxxxxx
    user: xxxxxxx
    pass: xxxxxxx
    DBname: xxxxxxx
    host: xxxxxxx
    SSLmode: xxxxxxx
  Dst:
    protocol: xxxxxxx
    user: xxxxxxx
    pass: xxxxxxx
    DBname: xxxxxxx
    host: xxxxxxx
    SSLmode: xxxxxxx
```

Go script
```go
// C contains the YAML configuration vars
var C YAMLConf 

// YAMLConf is the Yaml file struct
// Note: Struct fields must be public in order for unmarshal to correctly populate the data.
type YAMLConf struct {
	DBs struct {
		Src struct {
			Protocol string `yaml:"protocol"`
			User     string `yaml:"user"`
			Pass     string `yaml:"pass"`
			DBname   string `yaml:"DBname"`
			Host     string `yaml:"host"`
			SSLmode  string `yaml:"SSLmode"`
		}
		Dst struct {
			Protocol string `yaml:"protocol"`
			User     string `yaml:"user"`
			Pass     string `yaml:"pass"`
			DBname   string `yaml:"DBname"`
			Host     string `yaml:"host"`
			SSLmode  string `yaml:"SSLmode"`
		}
	}
}

func init() {
	C.readYAMLConf()
}

func (c *YAMLConf) readYAMLConf() {
	// open YAML file
	pwd, _ := os.Getwd()
	yamlFilename := filepath.Join(pwd, "config", "conf.yml")

	// read the YAML file
	yamlFileB, err := ioutil.ReadFile(yamlFilename)
	if err != nil {
		err = errors.Wrap(err, "ioutil.ReadFile(yamlFile) error")
		fmt.Printf("%+v\n\n", err)
		log.Fatal(err)
	}

	//  YAML file parsing
	err = yaml.Unmarshal(yamlFileB, &c)
	if err != nil {
		err = errors.Wrap(err, "unmarshal YAML file error")
		fmt.Printf("%+v\n\n", err)
		log.Fatalf("error: %v", err)
	}
	fmt.Printf("--- t:\n%v\n\n", c)  <------------- REMAINS EMPTY
}
```

 I had a successful attempt previously by using a single DB, but since I need to deal with 2 DBs and add a second nested level, it's not working anymore. 

Thanks for your help
