### ISSUE TITLE
index out of range [1536] with length 1536 [recovered]

### ISSUE THREAD

**Issue by Jacky2** [go-yaml/yaml#615]
**Version:** gopkg.in/yaml .v3

**Problem occurred:** index out of range [1536] with length 1536 [recovered]

**Reappear**: yaml file is followed by many lines of comments. If the comment character > 1534, an error will be reported

**Temporary solution:** leave more blank lines in comment lines

But in version gopkg.in/yaml . V2 will not have such a problem.

This is my code : 

```go
// JenkinsConfig 
type JenkinsConfig struct {
	Configs struct {
		Jobs []SrcJob
	}
}

// SrcJob struct
type SrcJob struct {
	Job map[string]string `yaml:"job"`
}

func (s *JenkinsConfig) GetConf(inputFile string) *JenkinsConfig {
	yamlFile, err := ioutil.ReadFile(inputFile)
	if err != nil {
		log.Printf("input file error!\n%v ", err)
	}
	err = yaml.Unmarshal([]byte(yamlFile), &s)
	if err != nil {
		log.Fatalf("Unmarshal yaml file error!\n%v", err)
	}
	return s
}

func main() {
	var s tools.JenkinsConfig

	s.GetConf("test.yaml")
	buildOption := s.Configs.Jobs[0].Job["jenkinsfileName"]
	fmt.Println(buildOption)
}

```

This is yaml file : 

```yaml
---
configs: 
  jobs: 
  - job: 
      jenkinsfileName: "web-test1"
      templatePath: "web-jenkinsfile.j2"
      jobDescription: "web-service"
      jobBuildKeepNum: "20"
      jobBuildKeepDays: "30"
      rollback_image_build_id: ""
      rollback_image: ""
      docker_tag_prefix: "dev"
      namespace: "default"
      app_port: "80"
      app_copy_num: "1"
  # - job: 
  #     jenkinsfileName: "web-test1"
  #     templatePath: "web-jenkinsfile.j2"
  #     jobDescription: "web-service"
  #     jobBuildKeepNum: "20"
  #     jobBuildKeepDays: "30"
  #     rollback_image_build_id: ""
  #     rollback_image: ""
  #     docker_tag_prefix: "dev"
  #     namespace: "default"
  #     app_port: "80"
  #     app_copy_num: "1"
  # - job: 
  #     jenkinsfileName: "web-test1"
  #     templatePath: "web-jenkinsfile.j2"
  #     jobDescription: "web-service"
  #     jobBuildKeepNum: "20"
  #     jobBuildKeepDays: "30"
  #     rollback_image_build_id: ""
  #     rollback_image: ""
  #     docker_tag_prefix: "dev"
  #     namespace: "default"
  #     app_port: "80"
  #     app_copy_num: "1"
  # - job: 
  #     jenkinsfileName: "web-test1"
  #     templatePath: "web-jenkinsfile.j2"
  #     jobDescription: "web-service"
  #     jobBuildKeepNum: "20"
  #     jobBuildKeepDays: "30"
  #     rollback_image_build_id: ""
  #     rollback_image: ""
  #     docker_tag_prefix: "dev"
  #     namespace: "default"
  #     app_port: "80"
  #     app_copy_num: "1"
  # - job: 
  #     jenkinsfileName: "web-test1"
  #     templatePath: "web-jenkinsfile.j2"
  #     jobDescription: "web-service"
  #     jobBuildKeepNum: "20"
  #     jobBuildKeepDays: "30"
  #     rollback_image_build_id: ""
  #     rollback_image: ""
  #     docker_tag_prefix: "dev"
  #     namespace: "default"
  #     app_port: "80"
  #     app_copy_num: "1"
  #     app_port: "80"
  #     app_copy_num: "1"
  #     app_port: "80"
  #     app_port: "80"   

```
