### ISSUE TITLE
Unmarshal then Marshal produces different result than the original content

### ISSUE THREAD

**Issue by neakor** [go-yaml/yaml#620]
As the title suggests, if we `Unmarshal` a `string` into `yaml.Node` then re-`Marshal` that node back into a `string`, the resulting `string` is different from the original. See the following example:

```
func exmapleIssue() {
  text := `apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "0"
  labels:
    "1"
  namespace: "2"
  annotations: "3"
spec:
  hosts:
  - cdd."2".svc.cluster.local
  http:
  - route:
    - destination:
        host: cdd."2"-first.svc.cluster.local
      weight: 22
  #1
  - route:
    - destination:
        host: cdd."2"-second.svc.cluster.local
`

  // Unmarshal then re-marshal.
  var root yaml.Node
  yaml.Unmarshal([]byte(text), &root)
  result, _ := yaml.Marshal(&root)
}
```

The result is

```
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: "0"
  labels: "1"
  namespace: "2"
  annotations: "3"
spec:
  hosts:
  - cdd."2".svc.cluster.local
  http:
  - route:
    - destination:
        host: cdd."2"-first.svc.cluster.local
      weight: 22
  - #1
    route:
    - destination:
        host: cdd."2"-second.svc.cluster.local
```

There are two subtle differences where the resulting yaml is different from the source:
1. The `metadata.labels` field has been shifted upward, when the source had the value `"1"` on a new line indented. The re-marshaled string hast the value inlined with the key.
2. The comment `#1` right above the second `route` has been shifted upward in the `http` sequence.
