### ISSUE TITLE
First level is indented twice?

### ISSUE THREAD

**Issue by xrstf** [go-yaml/yaml#633]
Since https://github.com/go-yaml/yaml/commit/a5ece683394c3b88d90572e44d36c93aea492c2c, the first level of my YAML documents is indented with 4 spaces, yet every other level stays at 2: https://play.golang.org/p/UFEafwZx1Wk yields

```
users:
    - name: Foo
      lastname: Bar
      emails:
        - foo@bar.org
      friends:
        - name: Friend
          lastname: ""
          emails: []
          friends: []
names:
    - test
```

When i was expecting

```
users:
  - name: Foo
    lastname: Bar
    emails:
      - foo@bar.org
    friends:
      - name: Friend
        lastname: ""
        emails: []
        friends: []
names:
  - test
```

**Comment by abursavich** [comment]
In the Go implementation sequences were recessed to offset the `- ` indicator, which caused the output to look orderly and aesthetically pleasing, and this is no longer working.

Here's a larger example of orderly alignment: https://play.golang.org/p/pPekV1RX5Ah

expecting:
```yaml
map:
    map:
        map:
            map: {}
            seq: []
        seq:
          - map: {}
          - seq: []
    seq:
      - map:
            map: {}
            seq: []
      - seq:
          - map: {}
          - seq: []
seq:
  - map:
        map:
            map: {}
            seq: []
        seq:
          - map: {}
          - seq: []
  - seq:
      - map:
            map: {}
            seq: []
      - seq:
          - map: {}
          - seq: []
```

got:
```yaml
map:
    map:
        map:
            map: {}
            seq: []
        seq:
            - map: {}
            - seq: []
    seq:
        - map:
            map: {}
            seq: []
        - seq:
            - map: {}
            - seq: []
seq:
    - map:
        map:
            map: {}
            seq: []
        seq:
            - map: {}
            - seq: []
    - seq:
        - map:
            map: {}
            seq: []
        - seq:
            - map: {}
            - seq: []
```
