### ISSUE TITLE
v3: dumps indenting not coherent with v2

### ISSUE THREAD

**Issue by sylr** [go-yaml/yaml#647]
The way v3 indents dumps by default is different from v2 and I think it shouldn't be:

- default indenting is now 4 spaces instead of 2
- list items are now shifted right instead of being vertically aligned with the key

```yaml
a: Easy! v2
b:
  c: 2
  d:
  - 3
  - 4
```

```yaml
a: Easy! v3
b:
    c: 2
    d:
        - 3
        - 4
```

I know it won't matter but I personally prefer the looks of the first dump.

Also I've seen this change break tests that rely on yaml string equality.
