### ISSUE TITLE
v3: (Encoder) setting indentation for sequences

### ISSUE THREAD

**Issue by starkers** [go-yaml/yaml#661]
Heya  ..amateur gopher here so go easy on me please..

I'm looking at the code on https://github.com/wangkuiyi/yamlfmt which is using v3

With a (eg stdout) stream I can see how the code uses an `Encoder` which is great, and I can easily see how the indent is modified via: https://pkg.go.dev/gopkg.in/yaml.v3#Encoder.SetIndent

What I'm trying todo however is set the indent level for the list/items.. EG:
currently:

```yaml
doc:
  key: foo
  items:
    - one
    - two
```
but I'd like a more compact:

````yaml
doc:
  key: foo
  items:
  - one
  - two
````
I cannot see any such receiver function on the `*Encoder` so I'm not certain how to do this am I missing something or is it just not implemented?
