### ISSUE TITLE
whole number floats parsed as integers

### ISSUE THREAD

**Issue by pguduru** [go-yaml/yaml#671]
If the Yaml contains a number like 3.0 it  is parsed/converted into 3. 
See below yaml and its corresponding JSON. It seems to however, work as expected for numbers like 3.01. 
```
appconfig:
  someval: 3.001
  someval1: 3.0
  someval2: 3.1
  someval3: !!float64 3.0
  someval4: "3.0"
```

```
{
  someval:3.001
  someval1:3
  someval2:3.1
  someval3:"3.0"
  someval4:"3.0"
}
```

Here are other downstream issues related to this.

https://github.com/helm/helm/issues/8978
https://github.com/helm/helm/issues/8799#issuecomment-698379753
