### ISSUE TITLE
 The content of my yaml file cannot be deserialized

### ISSUE THREAD

**Issue by thep0y** [go-yaml/yaml#687]
config.yaml
```yaml
databases:
  development:
    username: root
    password: root
    host: localhost
  production:
    username: example
    password: example
    host: example.com
```

main.go
```go
package main

import (
	"fmt"
	"io/ioutil"

	"gopkg.in/yaml.v2"
)

type Database struct {
	Username string
	Password string
	Host     string
}

type Config struct {
	dbs map[string]Database `yaml:"databases"`
}

func main() {
	s := Config{}
	file, err := ioutil.ReadFile("config.yaml")
	if err != nil {
		panic(err)
	}
	err = yaml.Unmarshal(file, &s)
	if err != nil {
		panic(err)
	}
	fmt.Println(s)
        // output
        // {map[]}
}
```

How can I fix my code?
