### ISSUE TITLE
Unmarshal handlers and YAML anchors (v3)

### ISSUE THREAD

**Issue by darh** [go-yaml/yaml#692]
I'm trying to unmarshal YAML document that can use (so, optional) anchors.

Example of the yaml doc:
```
# ...
  recordLookup: &recordLookup
    recordID:
      required: true
# ...
functions:
  composeRecordLookupByID:
    params:
      <<: *recordLookup
      recordID:
        required: false

```

I'm using UnmarshalYAML to decode `params` map into ordered sequence.
As soon as I introduce the anchor (as in example) decoder gives me an intermediate node that handles that anchor.
Situation gets even worse when multiple anchors are merged (`<<: [ *recordBase, *recordModify ]`).

So, the only solution that I have right now is settle with decoding into `map[string]...` that's gracefully handled by internal decoder functions. Correct?

What would be the way round this? Should I "denormalize" anchored nodes into a simple(r) struct?
Could lib handle this more gracefully somehow?

TBH: 90% of my custom unmarshal functions is for a) handling mapped nodes into ordered sequence, using keys as one of the values for value struct prop b) gracefully handling map and sequence definitions.

**Comment by niemeyer** [comment]
It's not clear from the description what the issue being reported is. You can either decode the data into a value, or you can decode the data into an intermediate value. With v3 you can preserve anchors for later decoding. From the comment it sounds like you already know about both cases, so what's the actual issue?

**Comment by darh** [comment]
Apologies. Let me try to explain with a more detailed example:

I'm trying make YAML files as readable as possible, and for me this means defining list of this as map.
So, instead of forcing users to sequence:
```yaml
list:
  - name: foo
    otherprops: {}
  - name: bar
    otherprops: {}
  - name: baz
    otherprops: {}
```

I prefer map:
```yaml
list:
  foo:
    otherprops: {}
  bar:
    otherprops: {}
  baz:
    otherprops: {}
```

And, wherever it's needed, both formats.
Problem with the map is, as we know, the fact that go does not keep them sorted. To circumvent that + to support both seq&map, I define my structs & unmarshal fn like:

```go
type (
  Item struct { Name string; OtherProps interface{} }
  ItemSet []*Item
)

func (s ItemSet) UnmarshalYAML(n *yaml.Node) error {
  // gracefully handle both seq and map
}
```

This works w/o a problem if no anchors are used. When they are, parsing it like this fails.
Please see full example https://gist.github.com/darh/74b32006be6fde8ca9f689f5308ce6bb
I want to get to same result all 5 examples in the 1st set when ItemSet type is used for parsing

So, I am totally aware that this is how yaml lib works and this is not a request to change this behaviour.
I just see that there is a lot of work done in the lib to ensure anchors are correctly processed and unmarshaled my question is
if there is a possibility to get it by 
a) exporting some internal functions that would allow easier parsing
b) lib providing some kind of "denormalizer" func (assuming we call yaml doc with anchors normalized, using db terminology) function that would resolve all anchors into a simpler structure or 
c) providing some kind of UnmarshalSimpleYAML() that would again, get access to simpler node structure like with b)

Hope this makes more sense now
