### ISSUE TITLE
v3: Head comment confused with foot comment

### ISSUE THREAD

**Issue by mruzicka** [go-yaml/yaml#695]
The following YAML document:
```yaml
spec:
    resources:
        # need more cpu upon initialization, therefore burstable class
        requests:
            cpu: 100m
            memory: 32Mi
        limits:
            cpu: 500m
            memory: 128Mi
```
when decoded into a  `yaml.Node` & then encoded again **on linux while the input document uses Windows line breaks** results in the following output:
```yaml
spec:
    resources:
        requests:
            cpu: 100m
            memory: 32Mi
        # need more cpu upon initialization, therefore burstable class

        limits:
            cpu: 500m
            memory: 128Mi
```
Please note the misplaced comment on the `spec.resources.requests` attribute.

### Additional info
- the immediate cause of the problem is that the comment is set as a `FootComment` (instead of the expected `HeadComment`) on the `yaml.Node` representing the attribute in question
- it does not happen when the input document uses UNIX line breaks
