### ISSUE TITLE
v3: preserve comments lines and indents after unmarshal -> marshal

### ISSUE THREAD

**Issue by Unix4ever** [go-yaml/yaml#709]
I wonder if it is possible to preserve the same positions for all decoded comments, when you unmarshal into `yaml.Node` and then marshal that `yaml.Node` back to yaml.

So for example:

```yaml
 block1:
    # the comment
    map:
        key1: a
        key2: b
    
    # foot comment
block2:
    hi: there
```

Turns into:
```yaml
 block1:
    # the comment
    map:
        key1: a
        key2: b
        # foot comment
block2:
    hi: there
```

Where foot comment changes it's indent and becomes foot comment of key2 (?).

Here's the code snippet:

```go
package main

import (
	"log"
	"strings"
	
	yaml "gopkg.in/yaml.v3"
)

func main() {
	var node yaml.Node
	
	data := []byte(strings.TrimSpace(`
block1:
    # the comment
    map:
        key1: a
        key2: b
    
    # foot comment
block2:
    hi: there

`))

	log.Printf("INPUT:\n %s", data)

	if err := yaml.Unmarshal(data, &node); err != nil {
		log.Fatalf("Unmarshalling failed %s", err)
	}
	
	results, err := yaml.Marshal(node.Content[0])
	if err != nil {
		log.Fatalf("Marshalling failed %s", err)
	}
	
	log.Printf("RESULT:\n %s", results)
}
```

https://play.golang.org/p/BtzerXV8ofI
It looks like the comment is attached to the last element in the map, instead of attaching it to the map.

Do you think it's a bug in the library? Or that's intended behavior? Is there any workaround for that?

**Comment by niemeyer** [comment]
On a first sight this seems to be a bug. It should remain as a foot comment of the key, otherwise it'll keep walking down the hierarchy on future encode/decode cycles. I'll have a look at this on the next update.

Thanks for the report.

**Comment by wburningham** [comment]
@niemeyer how big of a lift is it to fix this bug? I also have seen this issue.

**Comment by rafaela-soares** [comment]
Is there any update about this issue? I am facing a similar problem.

Original file content:
```
---
# this playbook creates users and projects in openstack,
# it's used for a "local authentication" mode, not for SSO

- name: Playbook to Create users and Projects in Openstack
  hosts: localhost
  collections:
    - openstack.cloud
  tasks:
    - name: 'Ensure Projects are as defined'
      include: subroutines/openstack_per_project_actions.yaml

    - name: 'Create Users in Openstack'
      openstack.cloud.identity_user:
        state: present
        name: "{{ add_user.name }}"
        password: "{{ all_openstack_default_pass }}"
        email: "{{ add_user.email }}"
        # kics-scan ignore-line
        update_password: on_create
        default_project: "{{ add_user.orgunit }}"
        domain: default
      loop: "{{ users_present }}"
      loop_control:
        loop_var: add_user
```

After after unmarshal -> marshal:

```
# this playbook creates users and projects in openstack,

# it's used for a "local authentication" mode, not for SSO
- name: Playbook to Create users and Projects in Openstack
  hosts: localhost
  collections:
    - openstack.cloud
  tasks:
    - name: 'Ensure Projects are as defined'
      include: subroutines/openstack_per_project_actions.yaml
    - name: 'Create Users in Openstack'
      openstack.cloud.identity_user:
        state: present
        name: "{{ add_user.name }}"
        password: "{{ all_openstack_default_pass }}"
        email: "{{ add_user.email }}"
        # kics-scan ignore-line

        update_password: on_create
        default_project: "{{ add_user.orgunit }}"
        domain: default
      loop: "{{ users_present }}"
      loop_control:
        loop_var: add_user
```
