### ISSUE TITLE
Parser does not fail for non-unique Map keys - error handling

### ISSUE THREAD

**Issue by ipapast** [go-yaml/yaml#745]
Hello there,
I was wondering how error handling is done in this pkg:

I've noticed a case where we have duplicate keys in a YAML doc, but the parser does not fail on that. According to the YAML specification, shouldn't that be an error?  http://www.yaml.org/spec/1.2/spec.html#id2764044

> The content of a mapping node is an unordered set of key: value node pairs, with the restriction that each of the keys is unique.

An example of a yaml doc with duplicate key of 'Resource1':
```
Resources:
  Resource1:
    Type: AWS::EC2::Instance
    Properties:
      KeyName: "test"
  Denied:
    Type: AWS::EC2::Instance
  Resource1:
    Type: AWS::EC2::Something
```
You can also try this online in a YAML validator: https://onlineyamltools.com/validate-yaml
![image](https://user-images.githubusercontent.com/6989529/120887682-2fcf4a80-c5ec-11eb-9bc9-156a573d6480.png)

Some online validators fail and some do not. However, other parser libraries handle this case as an error.

This is parsed by go-yaml and the result is getting the last value of the duplicate key.
```
Resources: 
  Denied: 
    Type: "AWS::EC2::Instance"
  Resource1: 
    Type: "AWS::EC2::Something"
```

Is there any documentation available where I can find how we handle errors in this library? 
What do we consider a parser Error and what not? Is there a way to differentiate between a "validation error" and a "syntax error"?
Do you have any plans to test against the YAML test suite? https://github.com/yaml/yaml-test-suite 

Thank you
