### ISSUE TITLE
Does this library support YAML formatting?

### ISSUE THREAD

**Issue by 030** [go-yaml/yaml#795]
I wonder whether it possible to read a file using this library and then to get a formatted output.

Input:

```
---
aggregationRule:
    clusterRoleSelectors:
        
        - matchLabels:
              a: "true"
        - matchLabels:
              b: "true"
        - matchLabels:
              c: "true"
```

Expected output:

```
---
aggregationRule:
  clusterRoleSelectors:
    - matchLabels:
        a: "true"
    - matchLabels:
        b: "true"
    - matchLabels:
        c: "true"

```
