### ISSUE TITLE
Questionable mapping node merge behavior

### ISSUE THREAD

**Issue by bjaglin** [go-yaml/yaml#81]
It seems that the interpretation of the [specification for merge](http://yaml.org/type/merge.html) is different than other parsers (PyYAML, JS-YAML, SnakeYAML), and in my opinion incorrect (although I do happen to rely on it for some "features").

I have found that when merging a single mapping node into a target mapping, values for keys that are present in that source mapping and had _previously_ been declared in the target mapping are overriding the existing ones. Other parsers' interpretation of the spec is that values in the source mapping should be completely ignored:

> If the value associated with the key is a single mapping node, each of its key/value pairs is inserted into the current mapping, unless the key already exists in it

I ran into this when [bumping from v1 to v2](https://github.com/michaelsauter/crane/pull/146), which resulted in a slightly changed behavior when the source value is a mapping but not the target one (in that particular case, going in the direction of other parsers' interpretation, but breaking a behavior I had taken for granted).

Tests exhibiting the current v2 behavior against the expected one are available at https://github.com/bjaglin/yaml/commit/3697451b30b0375268a30c23321f282978da0f14:

```
anchors:
  list:
    - &FOO { empty: notreally, flat: false, nested: { foo: merged } }

# All the following maps should be equal:

plain:
  empty:
  flat: true
  nested:
    foo: foo
    bar: bar

mergeBefore:
  << : *FOO
  empty:
  flat: true
  nested:
    foo: foo
    bar: bar

mergeAfter:
  empty:
  flat: true
  nested:
    foo: foo
    bar: bar
  << : *FOO
```

```
----------------------------------------------------------------------
FAIL: decode_test.go:935: S.TestMergeMap

decode_test.go:949:
    c.Assert(test, DeepEquals, want, Commentf("test %q failed", name))
... obtained map[interface {}]interface {} = map[interface {}]interface {}{"empty":"notreally", "flat":false, "nested":map[interface {}]interface {}{"foo":"merged"}}
... expected map[interface {}]interface {} = map[interface {}]interface {}{"empty":interface {}(nil), "flat":true, "nested":map[interface {}]interface {}{"foo":"foo", "bar":"bar"}}
... test "mergeAfter" failed


----------------------------------------------------------------------
FAIL: decode_test.go:953: S.TestMergeMapStruct

decode_test.go:971:
    c.Assert(test, Equals, want, Commentf("test %q failed", name))
... obtained yaml_test.Data = yaml_test.Data{Flat:false, Nested:yaml_test.Nested{Foo:"merged", Bar:"bar"}}
... expected yaml_test.Data = yaml_test.Data{Flat:true, Nested:yaml_test.Nested{Foo:"foo", Bar:"bar"}}
... test "mergeAfter" failed

```
