### ISSUE TITLE
yaml to struct - merge behavior : deep vs shallow merge 

### ISSUE THREAD

**Issue by kansalarchit** [go-yaml/yaml#818]
It seems like anchor merge behaves differently depending on the golang struct provided.

With a simple golang interface{} object, the conversion results in shallow merge. e.g.:

```
top:
  config: &config
    key1: value1
    map1: 
      mapkey1: value1
      mapkey2: value2

  otherconfig:
    <<: *config
    map1:
      mapkey1: some-other-value
```

results in (Shallow Merge)
```
top:
  config: &config
    key1: value1
    map1: 
      mapkey1: value1
      mapkey2: value2

  otherconfig:
    key1: value1
    map1:
      mapkey1: some-other-value
```

whereas when we provide a specific golang struct, such as

```
type top struct  {
  type config struct {
    key1 string,
    type map1 struct {
      mapkey1 string,
      mapkey2 string
      ...
    }
    ...
  }
  ...
}
```

For the same input, we get: (Deep Merge)
```
top:
  config: &config
    key1: value1
    map1: 
      mapkey1: value1
      mapkey2: value2

  otherconfig:
    key1: value1
    map1:
      mapkey1: some-other-value
      mapkey2: value2
```

This looks like inconsistent behavior and based on https://yaml.org/type/merge.html I believe we should always prefer shallow merge.

Can a flag be added to the parser so that we can choose to ignore deep merge even when parser knows the resulting struct ?
