### ISSUE TITLE
embedded struct fields not being parsed

### ISSUE THREAD

**Issue by cospotato** [go-yaml/yaml#859]
```golang
type HTTPGetAction struct {
        Path string `json:"path,omitempty"`
}

type Handler struct {
        HTTPGet *HTTPGetAction `json:"httpGet,omitempty"`
}

type Probe struct {
        Handler `json:",inline"`
}

type Data struct {
        LivenessProbe *Probe `json:"livenessProbe,omitempty"`
}
```

```yaml
livenessProbe:
  httpGet:
    path: /healthz
```

Hello community. I got `data.LivenessProbe == nil` with the example before.
