### ISSUE TITLE
golang nested inherit struct is not flattened when marshal to YAML 

### ISSUE THREAD

**Issue by taiyang-li** [go-yaml/yaml#868]
``` golang
type DBConfig struct {
	Description string
	Host        string
	Port        string
	User        string
	Password    string
	Db          string
	Cluster string
	Params  map[string]string
}

type CHDBConfig struct {
	DBConfig `yaml:"db_config"`

	ForHiveQuery bool `yaml:"for_hive_query"`
	HiveCluster string `yaml:"hive_cluster"`
	RangerServiceName string `yaml:"ranger_service_name"`
	UseJBOD bool `yaml:"use_jbod"`
	CreateUserWhitelist []string `yaml:"create_user_whitelist"`
}


func main() {
	chConf := &conf.CHDBConfig{
		DBConfig: conf.DBConfig{
			Description: "hive_sg cluster",
			Host:        "localhost",
			Cluster:     "hive_sg",
			Params: map[string]string{
				"max_execution_time": "360",
			},
		},
		ForHiveQuery:      true,
		HiveCluster:       "sg",
		RangerServiceName: "data_power_online",
	}

	bs, _ := json.Marshal(chConf)
	println(string(bs))

	bs, _ = yaml.Marshal(chConf)
	println(string(bs))
}

```

output: 
```
{"Description":"hive_sg cluster","Host":"localhost","Port":"","User":"","Password":"","Db":"","Cluster":"hive_sg","Params":{"max_execution_time":"360"},"ForHiveQuery":true,"HiveCluster":"sg","RangerServiceName":"data_power_online","UseJBOD":false,"CreateUserWhitelist":null}

db_config:
  description: hive_sgc luster
  host: localhost
  port: ""
  user: ""
  password: ""
  db: ""
  cluster: hive_sg
  params:
    max_execution_time: "360"
for_hive_query: true
hive_cluster: sg
ranger_service_name: data_power_online
use_jbod: false
create_user_whitelist: []
``` 

We can see that in result of JSON Marshal: `DBConfig` is flattened, which is not in result of YAML Marshal.
