### ISSUE TITLE
Trailing line spaces in string block changes to a quoted string

### ISSUE THREAD

**Issue by lazychanger** [go-yaml/yaml#880]
[mikefarah/yq#1282](https://github.com/mikefarah/yq/issues/1282#issue-1319211850)

**data1.yml**
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: gwn-cm
  labels:
    app: gwn
    version: v1
data:
  config.yaml: |
    context: { }
    plugins: 
      - name: github-autosync
        package: github-api
        version: latest
        config: |
          api: sync
          apiConfigs:
            sync:
              apiType: triggerRepositoryMirrorSyncConfig
              config: |
                accounts:
                  - account: admin
                    token: admin
                    condition: {{ eq .Request.Body.project.name "devops" }}
                repository: {}
                repositoryId: {{ printf "%.0f" .Request.Body.repository.id | quote }}
```

**example code**
```golang

package main

import (
	"gopkg.in/yaml.v3"
        "os"
	"log"
)

func main() {
        data, _ := os.ReadFile("data1.yaml")

	ymlData := make(map[string]any)

	yaml.Unmarshal(data, &ymlData)

	newData, _ := yaml.Marshal(ymlData)
	log.Println(string(newData))
}
```

**print yaml**
```yaml
apiVersion: v1
data:
    config.yaml: "context: { }\nplugins: \n  - name: github-autosync\n    package: github-api\n    version: latest\n    config: |\n      api: sync\n      apiConfigs:\n        sync:\n          apiType: triggerRepositoryMirrorSyncConfig\n          config: |\n            accounts:\n              - account: admin\n                token: admin\n                condition: {{ eq .Request.Body.project.name \"devops\" }}\n            repository: {}\n            repositoryId: {{ printf \"%.0f\" .Request.Body.repository.id | quote }}"
kind: ConfigMap
metadata:
    labels:
        app: gwn
        version: v1
    name: gwn-cm
```

**step**
Any line in string-block ends with a space
```yaml
plugins: 
```
