### ISSUE TITLE
Incorrect parsing for Literal Style

### ISSUE THREAD

**Issue by myishay** [go-yaml/yaml#888]
I made quick check in a golang playground here: https://go.dev/play/p/uYvBdAw5u2V
the provided code is as follows:
```go
package main

import (
	"bytes"
	"fmt"
	"io"

	"gopkg.in/yaml.v3"
)

var content = `
spec:
  template:
    spec:
      containers:
        - name: app
          args:
            - "-c"
            - |

              echo "hello world"

`

func main() {
	yamlDecoder := yaml.NewDecoder(bytes.NewReader([]byte(content)))

	var err error
	for {
		var anyTypeStore interface{}
		err = yamlDecoder.Decode(&anyTypeStore)
		if err != nil {
			if err == io.EOF {
				break
			} else {
				// return nil, err
				panic(err)
			}
		}

		yamlByteArray, err := yaml.Marshal(anyTypeStore)
		if err != nil {
			// return nil, err
			panic(err)
		}
		fmt.Println(string(yamlByteArray))
	}
}
```

the code takes the original yaml:
```yaml
spec:
  template:
    spec:
      containers:
        - name: app
          args:
            - "-c"
            - |

              echo "hello world"
```
decodes it and marshals it back to a yaml byte array (and ultimately a file), and this is the result
```yaml
spec:
    template:
        spec:
            containers:
                - args:
                    - -c
                    - |4
                      echo "hello world"
                  name: app

```
which is an invalid yaml (the number after the `|` indicates the indentation that should be in this [Literal Style](https://yaml.org/spec/1.2.2/#literal-style), which should be `2` and not `4`.
For more information regarding block indentation indicator: https://yaml.org/spec/1.2.2/#block-indentation-indicator

BTW when using `gopkg.in/yaml.v2` it generates the expected output:
```yaml
spec:
  template:
    spec:
      containers:
      - args:
        - -c
        - |2

          echo "hello world"
        name: app
```

This is also related to an issue we encountered here https://github.com/datreeio/datree/issues/762
