### ISSUE TITLE
The space before \n causes confusion in the format of the structure after yaml.marshal

### ISSUE THREAD

**Issue by sologgfun** [go-yaml/yaml#908]
For examples, see
https://go.dev/play/p/x1Ret7HakLV
the only different between the input string is whether there are spaces before \n 
`listen: \"8081\"[space here]\n`
What causes formatting problems? How can I fix it?
```
=== RUN   TestMarshalYML
v1: config.yaml: |
  listen: "8081"
  host: "[2409:8c20:1833:2000::afd:9741]"
  port: "3306"
V2: 
config.yaml: |
  listen: "8081"
  host: "[2409:8c20:1833:2000::afd:9741]"
  port: "3306"

V3: 
config.yaml: |
    listen: "8081"
    host: "[2409:8c20:1833:2000::afd:9741]"
    port: "3306"

===================
v1: config.yaml: "listen: \"8081\" \nhost: \"[2409:8c20:1833:2000::afd:9741]\"\nport:
  \"3306\"\n"
V2: 
config.yaml: "listen: \"8081\" \nhost: \"[2409:8c20:1833:2000::afd:9741]\"\nport:
  \"3306\"\n"

V3: 
config.yaml: "listen: \"8081\" \nhost: \"[2409:8c20:1833:2000::afd:9741]\"\nport: \"3306\"\n"

--- PASS: TestMarshalYML (0.00s)
PASS

```
