### ISSUE TITLE
mapping key "<<" already defined

### ISSUE THREAD

**Issue by yxxhero** [go-yaml/yaml#914]
```yaml
templates:
  template1: &template1
    devel: true

  template2: &template2
    missingFileHandler: Warn
    values:
      - values1.yaml
      - values2.yaml

releases:
  - name: release2
    chart: ./helm
    <<: *template1
    <<: *template2
```

error: eading document at index 1: yaml: unmarshal errors:
  line 15: mapping key "<<" already defined at line 14

**Comment by perlpunk** [comment]
The "correct" solution would be to use:
```
releases:
  - name: release2
    chart: ./helm
    <<: [*template1, *template2]
```
Your variant is supported by some libraries, too, but the official way is to put more than one merge value in a sequence.
See also https://yaml.org/type/merge.html
