### ISSUE TITLE
map key override issue

### ISSUE THREAD

**Issue by yxxhero** [go-yaml/yaml#915]
```yaml
templates:
  myapp_default: &myapp_default
    labels:
      service: "myapp"

releases:
  - name: myapp-1
    <<: *myapp_default
    labels:
      myapp: myapp-1
```
expected:
```
templates:
  myapp_default: &myapp_default
    labels:
      service: "myapp"

releases:
  - name: myapp-1
    labels:
      myapp: myapp-1
      service: "myapp"
```
got:
```yaml
templates:
  myapp_default: &myapp_default
    labels:
      service: "myapp"

releases:
  - name: myapp-1
    labels:
      myapp: myapp-1
```

this expected behavior?
