### ISSUE TITLE
Can I marshal struct into YAML dictionary in one line?

### ISSUE THREAD

**Issue by yusiwen** [go-yaml/yaml#939]
Output should like below:

```yaml
---
test:
  dict: { key1: 'value1', key2: 2}
```

Can I marshal a struct into yaml dictionary in one line like `dict: { key1: 'value1', key2: 2}`?

Thanks!
