### ISSUE TITLE
README example is incorrect

### ISSUE THREAD

**Issue by intiluha** [go-yaml/yaml#946]
If you run the exact code from the README example, you will get different result than expected. The difference is in indentation
https://go.dev/play/p/HQ9JYa_wyNQ

README:
```
--- m dump:
a: Easy!
b:
  c: 2
  d:
  - 3
  - 4
```

reality:
```
a: Easy!
b:
    c: 2
    d:
        - 3
        - 4
```

Probably should fix either behaviour or README
