### ISSUE TITLE
Parsing sequence with map and strings

### ISSUE THREAD

**Issue by vanhalt** [go-yaml/yaml#97]
Hey there!

How would you parse this:

``` yaml
users:
- a: {sudo: true}
- b
```

Defining a structure either with map or string fails. Any advice?
