### ISSUE TITLE
Windows line endings issue

### ISSUE THREAD

**Issue by szymonGlomskiN** [go-yaml/yaml#987]
`file.yaml`
```yaml
paramX:
  x: 1
  # first comment line
  # second comment line
  y:
```

``` go
var nodes yaml.Node
inData, _ := os.ReadFile("file.yaml")
_ = yaml.Unmarshal(inBytes, &nodes) 
```

When `x` has a value and `file.yaml` has windows line endings. `first comment line` is ommited in `nodes`
