### ISSUE TITLE
Indentation problem

### ISSUE THREAD

**Issue by davidebettio** [go-yaml/yaml#992]
Hi,

how could I indent in this way?

```
DNAT:
- DST_DEV: GREEN&ORANGE&BLUE
  DST_IP: 192.168.0.10
  DST_PORT: '8080'
  ENABLED: 'on'
  FILTER_TARGET: ALLOW
  LOG: 'off'
  NAT_TARGET: DNAT
  PROTO: tcp
  REMARK: test1
  SRC_DEV: ''
  SRC_IP: 127.0.0.1
  TARGET_IP: 10.0.0.10
  TARGET_PORT: '8081'
SNAT: []
```

with `SetIndent(2)` the result is:

```
DNAT:
  - DST_DEV: GREEN&ORANGE&BLUE
    DST_IP: 192.168.0.10
    DST_PORT: "8080"
    ENABLED: "on"
    FILTER_TARGET: ALLOW
    LOG: "off"
    NAT_TARGET: DNAT
    PROTO: tcp
    REMARK: test1
    SRC_DEV: ""
    SRC_IP: 127.0.0.1
    TARGET_IP: 10.0.0.10
    TARGET_PORT: "8081"
SNAT: []
```
